Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,46 +41,54 @@ jobs:
         echo "${{ github.run_id }}"
         echo "RETURN_STRING=$return_string" >> $GITHUB_ENV
       continue-on-error: true
-
+    
     - name: Apiiro API Results Scan
       run: |
         max_retries=20
         current_retry=0
     
         while true; do
-            # Save the output and HTTP status in separate variables
-            response=$(curl -sS -w "%{http_code}" --insecure --retry 15 --retry-max-time 900 --retry-delay 45 --location --request GET "https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results" \
+            response=$(curl -sS --insecure --retry 15 --retry-max-time 900 --retry-delay 45 --location --request GET "https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results" \
             --header 'Content-Type: application/json' \
-            --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}' -o temp_response.json)
-            http_status=$(tail -n1 temp_response.json) # Get the last line where http status is stored
-            response=$(sed '$ d' temp_response.json) # Remove the last line containing the HTTP status
+            --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}')
     
-            if [ "$http_status" -ne 200 ]; then
-                echo "Request failed with HTTP status $http_status"
-                if [ "$http_status" -eq 503 ]; then
-                    echo "Service unavailable. Retrying in 5 seconds..."
-                    sleep 5
-                else
-                    echo "Response: $response"
-                    exit 1
-                fi
+            # Increment retry counter
+            ((current_retry++))
+    
+            # Check if the response is valid JSON
+            if ! echo "$response" | jq empty 2>/dev/null; then
+                echo "Received an invalid JSON response. Waiting before the next check..."
+                sleep 5
             else
-                # Parse the response with jq
-                buildPassed=$(echo "$response" | jq '.buildPassed')
+                echo "--------------------------------"
+                echo "API Response Summary:"
+                echo "--------------------------------"
+                echo "$response" | jq -r '.summary'
+                echo "--------------------------------"
+    
+                # Checking and printing scan results if available
+                if echo "$response" | jq -e '.scanResults' >/dev/null 2>&1; then
+                    echo "API Scan Results:"
+                    echo "$response" | jq -r '.scanResults[] | "Rule Name: \(.ruleName), Matched: \(.ruleMatched)"'
+                else
+                    echo "No scan results found or 'scanResults' key is missing."
+                fi
+                echo "--------------------------------"
+    
+                # Check buildPassed status
+                buildPassed=$(echo "$response" | jq -r '.buildPassed')
                 if [[ "$buildPassed" == "true" ]]; then
                     echo "Pipeline can continue. Apiiro scan passed."
                     exit 0
                 else
-                    echo "Pipeline cannot continue. Apiiro scan indicated failure or was inconclusive."
+                    echo "Unexpected JSON format, missing 'buildPassed' key, or Apiiro scan indicated failure."
                     exit 1
                 fi
             fi
     
-            ((current_retry++))
+            # Break if max retries reached
             if [[ $current_retry -ge $max_retries ]]; then
-                echo "Max retries reached. Exiting."
+                echo "Max retries reached without a conclusive result. Exiting."
                 exit 1
             fi
         done
-        rm temp_response.json # Clean up
-    
