Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,52 +42,47 @@ jobs:
         echo "RETURN_STRING=$return_string" >> $GITHUB_ENV
       continue-on-error: true
 
-    # Apiiro API Results Scan
     - name: Apiiro API Results Scan
       run: |
         max_retries=20
         current_retry=0
-
+    
         while true; do
-            response=$(curl -sS --insecure --retry 15 --retry-max-time 900 --retry-delay 20 -f --location --request GET "https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results" \
+            response=$(curl -sS --insecure --retry 15 --retry-max-time 900 --retry-delay 45 --location --request GET "https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results" \
             --header 'Content-Type: application/json' \
             --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}')
-
+    
             # Increment retry counter
             ((current_retry++))
-
+    
             # Check if the response is valid JSON
             if ! echo "$response" | jq empty 2>/dev/null; then
                 echo "Received an invalid JSON response. Waiting before the next check..."
-                sleep 10
-            # Directly check for '503' in the response body
-            elif echo "$response" | grep -q "503"; then
-                echo "Scan is still in progress. Waiting for the next check..."
-                sleep 10
+                sleep 5
             else
-                # Handle successful response here
-
-                echo "API Response Summary:"
-                echo "$response" | jq -r '.summary'
-                echo "---------------------"
-                echo "API Scan Results:"
-                echo "$response" | jq -r '.scanResults[]'
-                echo "---------------------"
-                
-                
-                # Check buildPassed status
-                if echo "$response" | jq -e '.buildPassed' 2>/dev/null | grep -q "true"; then
+                # Check for 'buildPassed' status in the JSON response
+                buildPassed=$(echo "$response" | jq '.buildPassed')
+    
+                if [ "$buildPassed" == "true" ]; then
                     echo "Pipeline can continue. Apiiro scan passed."
+                    echo "API Response Summary:"
+                    echo "$response" | jq -r '.summary'
+                    echo "---------------------"
+                    echo "API Scan Results:"
+                    echo "$response" | jq -r '.scanResults[]'
                     exit 0
+                elif [ "$buildPassed" == "false" ]; then
+                    echo "Pipeline cannot continue. Apiiro scan failed."
+                    exit 1
                 else
                     echo "Unexpected JSON format or missing 'buildPassed' key."
-                    exit 1
+                    sleep 5
                 fi
             fi
-
+    
             # Break if max retries reached
             if [[ $current_retry -ge $max_retries ]]; then
-                echo "Max retries reached. Exiting."
+                echo "Max retries reached without a conclusive result. Exiting."
                 exit 1
             fi
         done
