Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,38 +45,49 @@ jobs:
     # Apiiro API Results Scan
     - name: Apiiro API Results Scan
       run: |
-       while true; do
-            response=$(curl -sS --insecure --retry 15 --retry-max-time 900 --retry-delay 45 --location --request GET 'https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results' \
-            --header 'Content-Type: application/json' \
-            --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}')
-        
-            # Check if the response is valid JSON
-            if ! echo "$response" | jq empty 2>/dev/null; then
-                echo "Received an invalid JSON response. Waiting before the next check..."
-                sleep 5
-                continue
-            fi
-        
-            # Check for HTTP 503 Service Unavailable
-            if echo "$response" | grep -q "HTTP.*503"; then
-                echo "Scan is still in progress. Waiting for the next check..."
-                sleep 5  # Wait 5 seconds before the next iteration
-            else
-                # Print the API response summary and scan results
-                echo "API Response Summary:"
-                echo "$response" | jq -r '.summary'
-                echo "---------------------"
-                echo "API Scan Results:"
-                echo "$response" | jq -r '.scanResults[]'
-                echo "---------------------"
+            max_retries=20
+            current_retry=0
+
+            while true; do
+                response=$(curl -sS --insecure --retry 15 --retry-max-time 900 --retry-delay 45 --location --request GET 'https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.RETURN_STRING }}/results' \
+                --header 'Content-Type: application/json' \
+                --header 'Authorization: Bearer $(bearer)')
                 
-                # Check buildPassed status
-                if echo "$response" | jq -e '.buildPassed' 2>/dev/null | grep -q "true"; then
-                    echo "Pipeline can continue. Apiiro scan passed."
-                    exit 0
+                # Increment retry counter
+                ((current_retry++))
+
+                # Check if the response is valid JSON
+                if ! echo "$response" | jq empty 2>/dev/null; then
+                    echo "Received an invalid JSON response. Waiting before the next check..."
+                    sleep 5
+                # Directly check for '503' in the response body
+                elif echo "$response" | grep -q "503"; then
+                    echo "Scan is still in progress. Waiting for the next check..."
+                    sleep 5
                 else
-                    echo "Unexpected JSON format or missing 'buildPassed' key."
+                    # Handle successful response here
+
+                    echo "API Response Summary:"
+                    echo "$response" | jq -r '.summary'
+                    echo "---------------------"
+                    echo "API Scan Results:"
+                    echo "$response" | jq -r '.scanResults[]'
+                    echo "---------------------"
+                    
+                    
+                    # Check buildPassed status
+                    if echo "$response" | jq -e '.buildPassed' 2>/dev/null | grep -q "true"; then
+                        echo "Pipeline can continue. Apiiro scan passed."
+                        exit 0
+                    else
+                        echo "Unexpected JSON format or missing 'buildPassed' key."
+                        exit 1
+                    fi
+                fi
+
+                # Break if max retries reached
+                if [[ $current_retry -ge $max_retries ]]; then
+                    echo "Max retries reached. Exiting."
                     exit 1
                 fi
-            fi
-        done
+            done
